import SwiftUI

// Generated by Supernova - do not modify manually
extension Text {

    func textStyleTextRegular() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 14))
    }

    func textStyleTextSRegular() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 13))
    }

    func textStyleTextXsRegular() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 11))
    }

    func textStyleTextLRegular() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 16))
    }

    func textStyleTextXlRegular() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 18))
    }

    func textStyleText2XlRegular() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 20))
    }

    func textStyleText3XlRegular() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 24))
    }

    func textStyleText4XlRegular() -> some View {
        return self
            .font(Font.custom("InterRegular", size: 30))
    }

    func textStyleTextMedium() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 14))
    }

    func textStyleTextSMedium() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 13))
    }

    func textStyleTextXsMedium() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 11))
    }

    func textStyleTextLMedium() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 16))
    }

    func textStyleTextXlMedium() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 18))
    }

    func textStyleText2XlMedium() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 20))
    }

    func textStyleText3XlMedium() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 24))
    }

    func textStyleText4XlMedium() -> some View {
        return self
            .font(Font.custom("InterMedium", size: 30))
    }

    func textStyleTextSemiBold() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 14))
    }

    func textStyleTextSSemiBold() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 13))
    }

    func textStyleTextXsSemiBold() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 11))
    }

    func textStyleTextLSemiBold() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 16))
    }

    func textStyleTextXlSemiBold() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 18))
    }

    func textStyleText2XlSemiBold() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 20))
    }

    func textStyleText3XlSemiBold() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 24))
    }

    func textStyleText4XlSemiBold() -> some View {
        return self
            .font(Font.custom("InterSemiBold", size: 30))
    }
}
