import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    func shadowShadow() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.1), radius: 2, x: 0, y: 1) 
    }

    func shadowShadow2() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.06), radius: 1, x: 0, y: 1) 
    }

    func shadowShadow3() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.2), radius: 1, x: 0, y: 0) 
    }

    func shadowShadowL() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.07), radius: 3, x: 0, y: 4) 
    }

    func shadowShadowL2() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.06), radius: 2, x: 0, y: 2) 
    }

    func shadowShadowL3() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.2), radius: 1, x: 0, y: 0) 
    }

    func shadowShadowXl() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.04), radius: 8, x: 0, y: 10) 
    }

    func shadowShadowXl2() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.1), radius: 3, x: 0, y: 4) 
    }

    func shadowShadowXl3() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.2), radius: 1, x: 0, y: 0) 
    }

    func shadowShadow2Xl() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.03), radius: 13, x: 0, y: 20) 
    }

    func shadowShadow2Xl2() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.08), radius: 5, x: 0, y: 8) 
    }

    func shadowShadow2Xl3() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.2), radius: 1, x: 0, y: 0) 
    }

    func shadowShadow3Xl() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.15), radius: 25, x: 0, y: 25) 
    }

    func shadowShadow3Xl2() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.2), radius: 1, x: 0, y: 0) 
    }

    func shadowShadowS() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.05), radius: 1, x: 0, y: 1) 
    }

    func shadowShadowS2() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.4), radius: 1, x: 0, y: 0) 
    }
}